### ISSUE TITLE
Something went wrong opening the port forward

### ISSUE THREAD

**Issue by apurb-coder** [surajbahadur591/Google-Colab-Scripts#2]
![ice_screenshot_20201231-194614](https://user-images.githubusercontent.com/55659698/103413744-cf516280-4ba0-11eb-8102-a4ad12eb401d.png)

**Comment by mathjonatha** [comment]
![image](https://user-images.githubusercontent.com/43009079/104945218-23c55200-5997-11eb-8dd9-ee77661cc4cd.png)

where it has: get_ipython().system_raw(r"curl -fsSL https://filebrowser.xyz/get.sh | bash")

replace with: get_ipython().system_raw(r"curl -fsSL https://filebrowser.org/get.sh | bash")
